### PR TITLE
Adding commits to releases. 

### PR DESCRIPTION
**Pull request by moisesrodriguez**
Added more parameters to the body so we could track releases by their commits according to https://blog.sentry.io/2017/05/01/release-commits.html

### CODE REVIEW

**Comment by moisesrodriguez** [comment]
@Sundarasan @Sujsun  is this something that will be considered?

**Comment by Sundarasan** [comment]
Test cases were failing in your branch @moisesrodriguez.

**Comment by moisesrodriguez** [comment]
@Sundarasan right. I fixed the typo.

**Comment by Sundarasan** [comment]
Thank you @moisesrodriguez.

**Pull request merged**
